import { useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { residentOptions, sampleNow, staffNames, usePortal } from './PortalContext'
import type { Incident } from './PortalContext'
import { Badge, csvDownload, includesSearch, Modal, Notice, Panel, Table } from './PortalUI'

export default function IncidentsPage() {
  const { incidents, setIncidents, setAlerts, search, print } = usePortal()
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  const [range, setRange] = useState('7')
  const [resident, setResident] = useState('All residents')
  const [type, setType] = useState('All types')
  const [status, setStatus] = useState('All statuses')
  const [modal, setModal] = useState<'followup' | 'family' | null>(null)
  const formRef = useRef<HTMLFormElement>(null)
  const [familyId, setFamilyId] = useState('INC-2041')
  const [familyText, setFamilyText] = useState('')
  const types = [...new Set(['Fall', 'Medication', 'Maintenance', 'Complaint', 'Other', ...incidents.map(i => i.type)])]
  const names = [...new Set(incidents.map(i => i.name))]
  const cutoff = new Date(sampleNow).getTime() - Number(range) * 86400000
  const visible = incidents.filter(i => includesSearch(search, i.id, i.name, i.unit, i.description, i.action, i.staff) && (range === 'all' || new Date(i.date).getTime() >= cutoff) && (resident === 'All residents' || resident === i.name) && (type === 'All types' || type === i.type) && (status === 'All statuses' || status === i.status))
  const headings = ['ID', 'Resident', 'Unit', 'Type', 'Date', 'Status', 'Staff', 'Action']
  const rows = visible.map(i => [i.id, i.name, i.unit, i.type, i.date.replace('T', ' '), i.status, i.staff || 'Unassigned', i.action])
  function save(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const data = new FormData(e.currentTarget); const person = residentOptions.find(r => r.name === data.get('resident'))!; const description = String(data.get('description') || '').trim(); const date = String(data.get('date') || '')
    if (!description) { setError('Enter an incident description.'); return }
    if (date > sampleNow) { setError('Use a date at or before the sample clock (6 October 2026, 12:00).'); return }
    const file = data.get('evidence') as File | null
    if (file?.size && (file.size > 10 * 1024 * 1024 || !['image/png', 'image/jpeg', 'application/pdf'].includes(file.type))) { setError('Choose a PNG, JPEG or PDF file up to 10 MB.'); return }
    const item: Incident = { id: `INC-${crypto.randomUUID().slice(0, 6).toUpperCase()}`, type: String(data.get('type')), name: person.name, unit: person.unit, date, location: String(data.get('location') || '').trim(), description, staff: String(data.get('staff') || ''), status: 'Pending', action: 'Awaiting follow-up.', evidence: file?.size ? file.name : '' }
    setIncidents(list => [item, ...list]); setError(''); e.currentTarget.reset(); setRange('all'); setResident('All residents'); setType('All types'); setStatus('All statuses'); setNotice(`${item.id} saved locally. Evidence filename only retained; no upload or file storage.`)
  }
  function followup(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const d = new FormData(e.currentTarget); const id = String(d.get('incident')); const action = String(d.get('action') || '').trim(); const staff = String(d.get('staff')); const nextStatus = String(d.get('status')) as Incident['status']
    if (!action) { setError('Enter the follow-up action.'); return }
    const item = incidents.find(i => i.id === id)!
    setIncidents(list => list.map(i => i.id === id ? { ...i, staff, status: nextStatus, action: `${i.action}\n${action}` } : i))
    if (item.alertId) setAlerts(list => list.map(a => a.id === item.alertId ? { ...a, responder: staff, actions: `${a.actions}\n${action}`.trim(), status: nextStatus === 'Completed' ? 'Resolved' : 'Pending' } : a))
    setNotice(`Follow-up saved for ${id}. Linked alert status updated where applicable.`); setModal(null)
  }
  return <div className="pp-main"><Notice>{notice}</Notice><div className="pp-incident-layout"><Panel title="＋ Log New Incident"><form ref={formRef} onSubmit={save}><label>Incident Type<select name="type" required defaultValue=""><option value="">Select type...</option>{['Fall', 'Medication', 'Maintenance', 'Complaint', 'Other'].map(t => <option key={t}>{t}</option>)}</select></label><label>Resident / Unit<select name="resident" required defaultValue=""><option value="">Select resident...</option>{residentOptions.map(r => <option value={r.name} key={r.name}>{r.name} · {r.unit}</option>)}</select></label><label>Date & Time<input type="datetime-local" name="date" required defaultValue={sampleNow} max={sampleNow} /></label><label>Location<input name="location" maxLength={120} placeholder="e.g. Dining hall" /></label><label>Description<textarea name="description" required maxLength={2000} placeholder="Provide a detailed account of the incident..." /></label><label>Assigned Staff<select name="staff" defaultValue=""><option value="">Unassigned</option>{staffNames.map(s => <option key={s}>{s}</option>)}</select></label><label className="pp-file">Attach Photo or Evidence<input type="file" name="evidence" accept="image/png,image/jpeg,application/pdf" /><span className="pp-muted">PNG, JPEG, PDF · up to 10 MB. Demo retains filename only; nothing is uploaded.</span></label>{error && !modal && <p className="sd-error" role="alert">{error}</p>}<div className="pp-actions"><button type="reset" onClick={() => setError('')}>Cancel</button><button className="sd-primary">Save Incident</button></div></form></Panel><div className="pp-stack">
      <Panel title="Follow-Up Actions" actions={<button className="sd-primary" onClick={() => { setModal('followup'); setError('') }}>＋ Add Follow-Up</button>}><Table label="Incident follow-up list"><thead><tr>{['ID / Type', 'Resident', 'Assigned Staff', 'Action Taken', 'Status'].map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{visible.map(i => <tr key={i.id}><th scope="row">{i.id}<br /><span className="pp-muted">{i.type}</span></th><td>{i.name}<br />{i.unit}</td><td>{i.staff || 'Unassigned'}</td><td style={{ whiteSpace: 'pre-line' }}>{i.action}{i.evidence && <p className="pp-muted">Filename: {i.evidence}</p>}</td><td><Badge value={i.status} /></td></tr>)}{!visible.length && <tr><td colSpan={5}>No incidents match your filters.</td></tr>}</tbody></Table><p className="pp-muted">{visible.length} of {incidents.length} incidents · Filters below apply to this list and exports.</p></Panel>
      <Panel title="Incident Reports & Analytics" actions={<><button onClick={() => print({ title: 'Incident Management Report', headings, rows })}>Print / Save PDF</button><button onClick={() => { csvDownload('communitycare-demo-incidents.csv', [headings, ...rows]); setNotice('Filtered incident summary exported as CSV.') }}>CSV</button></>}><div className="pp-filter"><label>Date Range<select value={range} onChange={e => setRange(e.target.value)}><option value="7">Last 7 sample days</option><option value="30">Last 30 sample days</option><option value="all">All sample dates</option></select></label><label>Resident<select value={resident} onChange={e => setResident(e.target.value)}><option>All residents</option>{names.map(n => <option key={n}>{n}</option>)}</select></label><label>Incident Type<select value={type} onChange={e => setType(e.target.value)}><option>All types</option>{types.map(t => <option key={t}>{t}</option>)}</select></label><label>Status<select value={status} onChange={e => setStatus(e.target.value)}>{['All statuses', 'Pending', 'Completed'].map(s => <option key={s}>{s}</option>)}</select></label></div><p className="pp-muted">Date filters are relative to the sample clock: 6 October 2026, 12:00.</p><div className="pp-report-options"><article><h3>Family Communication</h3><p>Write a family-facing summary for one resident. Internal staff notes are not copied automatically.</p><button onClick={() => { setFamilyId(visible[0]?.id || incidents[0].id); setFamilyText(''); setModal('family') }}>Prepare Family Summary</button></article><article><h3>Internal Management</h3><p>Preview filtered incident status and staff follow-up actions for management review.</p><button className="sd-primary" onClick={() => print({ title: 'Internal Incident Summary', headings, rows })}>Print Management Report</button></article></div></Panel>
    </div></div>
    {modal && <Modal title={modal === 'followup' ? 'Add Follow-Up' : 'Prepare Family Summary'} onClose={() => setModal(null)}>{modal === 'followup' ? <form onSubmit={followup}><label>Incident<select name="incident">{incidents.map(i => <option key={i.id} value={i.id}>{i.id} · {i.name}</option>)}</select></label><label>Assigned Staff<select name="staff">{staffNames.map(s => <option key={s}>{s}</option>)}</select></label><label>Action Taken<textarea name="action" required maxLength={1200} /></label><label>Status<select name="status"><option>Pending</option><option>Completed</option></select></label>{error && <p role="alert" className="sd-error">{error}</p>}<div className="sd-dialog-actions"><button type="button" onClick={() => setModal(null)}>Cancel</button><button className="sd-primary">Save Follow-Up</button></div></form> : <><label>Incident<select value={familyId} onChange={e => { setFamilyId(e.target.value); setFamilyText('') }}>{incidents.map(i => <option value={i.id} key={i.id}>{i.id} · {i.name}</option>)}</select></label><label>Family-facing summary<textarea value={familyText} onChange={e => setFamilyText(e.target.value)} maxLength={1500} /></label><p className="pp-muted">Review your wording before printing. This creates a local draft; it does not send a message or verify family access.</p><button className="sd-primary" disabled={!familyText.trim()} onClick={() => { const i = incidents.find(item => item.id === familyId)!; print({ title: 'Family Summary Draft', headings: ['Resident', 'Date', 'Summary'], rows: [[i.name, i.date.slice(0, 10), familyText.trim()]], note: 'User-written draft; review before sharing.' }) }}>Print / Save PDF Draft</button></>}</Modal>}
  </div>
}
