import { useState } from 'react'
import { staffNames, usePortal } from './PortalContext'
import { csvDownload, includesSearch, Panel, Table } from './PortalUI'

type Event = { day: string; group: string; type: string; seconds: number; staff: string }
const events: Event[] = Array.from({ length: 14 }, (_, d) => {
  const date = new Date(Date.UTC(2026, 8, 23 + d)).toISOString().slice(0, 10)
  return Array.from({ length: 6 + d % 5 }, (_, n) => ({ day: date, group: n % 2 ? 'West Wing' : 'East Wing', type: ['SOS', 'Fall', 'Geofence', 'Missed Check-in'][n % 4], seconds: 80 + ((d * 97 + n * 137) % 690), staff: staffNames[n % 3] }))
}).flat()
const taskCounts = [142, 128, 156]
function mean(values: number[]) { return values.length ? values.reduce((a, b) => a + b, 0) / values.length : 0 }
function duration(seconds: number) { const value = Math.round(seconds); return `${Math.floor(value / 60)}m ${String(value % 60).padStart(2, '0')}s` }

export default function ReportsPage() {
  const { search, print } = usePortal()
  const [range, setRange] = useState('7')
  const [group, setGroup] = useState('All Resident Groups')
  const lastDays = [...new Set(events.map(e => e.day))].slice(-Number(range))
  const selected = events.filter(e => lastDays.includes(e.day) && (group === 'All Resident Groups' || e.group === group))
  const days = lastDays.map(day => { const values = selected.filter(e => e.day === day).map(e => e.seconds); return { day, min: Math.min(...values), avg: mean(values), max: Math.max(...values), count: values.length } })
  const seconds = selected.map(e => e.seconds)
  const stats = [Math.min(...seconds), mean(seconds), Math.max(...seconds)]
  const usage = ['SOS', 'Fall', 'Geofence', 'Missed Check-in'].map(type => ({ type, count: selected.filter(e => e.type === type).length }))
  const staff = staffNames.map((name, index) => { const assigned = selected.filter(e => e.staff === name); return { name, tasks: taskCounts[index], alerts: assigned.length, response: duration(mean(assigned.map(e => e.seconds))), attendance: [98, 95, 100][index] } }).filter(s => includesSearch(search, s.name))
  const chartRows = days.map(d => [d.day, duration(d.min), duration(d.avg), duration(d.max), d.count])
  const staffRows = staff.map(s => [s.name, s.tasks, s.alerts, s.response, `${s.attendance}%`])
  const headings = ['Date', 'Fastest', 'Average', 'Longest', 'Alerts']
  const staffHeadings = ['Staff', 'Tasks (sample month)', 'Alerts (selected period)', 'Average Response', 'Attendance (sample month)']
  const points = (key: 'min' | 'avg' | 'max') => days.map((d, i) => `${55 + i * 480 / Math.max(days.length - 1, 1)},${275 - d[key] / 60 * 16}`).join(' ')
  const note = `Sample period ${lastDays[0]} to ${lastDays.at(-1)} · ${group}. Staff task totals and attendance use a fixed sample month.`
  function csv() { csvDownload('communitycare-demo-analytics.csv', [['CommunityCare analytics — sample data'], [note], ['Metric', 'Response'], ...['Fastest', 'Average', 'Longest'].map((m, i) => [m, duration(stats[i])]), [], headings, ...chartRows, [], ['Alert type', 'Count'], ...usage.map(u => [u.type, u.count]), [], staffHeadings, ...staffRows]) }
  return <div className="pp-main"><Panel title="Export Reports" actions={<><button className="sd-primary" onClick={() => print({ title: 'Reports & Analytics', headings: ['Section', 'Item', 'Value', 'Details'], rows: [...stats.map((s, i) => ['Response', ['Fastest', 'Average', 'Longest'][i], duration(s), 'Selected period']), ...days.map(d => ['Daily response', d.day, duration(d.avg), `Fastest ${duration(d.min)} / longest ${duration(d.max)} / ${d.count} alerts`]), ...usage.map(u => ['Usage', u.type, u.count, 'Selected period']), ...staff.map(s => ['Staff', s.name, `${s.alerts} alerts / ${s.response}`, `${s.tasks} monthly tasks / ${s.attendance}% monthly attendance`])], note })}>Print / Save PDF</button><button onClick={csv}>Export as CSV</button></>}><p className="pp-muted">{note} · Printing opens the browser dialog; choose Save as PDF.</p></Panel>
    <div className="pp-report-grid"><Panel title="Response Times"><div className="pp-metrics">{['Fastest Response', 'Average Response', 'Longest Response'].map((title, i) => <div key={title}>{title}<strong>{duration(stats[i])}</strong></div>)}</div><div className="pp-legend"><span style={{ color: '#388c42' }}>● Fastest</span><span style={{ color: '#c96f00' }}>● Average</span><span style={{ color: '#d84242' }}>● Longest</span></div><svg className="pp-chart" viewBox="0 0 580 325" role="img" aria-label="Daily response time chart in minutes. Exact values are available in the table below.">{[0, 3, 6, 9, 12, 15].map(n => <g key={n}><line x1="55" x2="535" y1={275 - n * 16} y2={275 - n * 16} stroke="#dbe6de" /><text x="22" y={279 - n * 16}>{n}</text></g>)}<text x="18" y="18">Minutes</text>{(['min', 'avg', 'max'] as const).map((key, i) => <polyline key={key} points={points(key)} fill="none" stroke={['#388c42', '#ef9000', '#f04f54'][i]} strokeWidth="2.5" />)}{days.map((d, i) => (i % (days.length > 7 ? 2 : 1) === 0) && <text key={d.day} x={55 + i * 480 / Math.max(days.length - 1, 1)} y="303" textAnchor="middle">{d.day.slice(5)}</text>)}</svg><details><summary>View response-time data</summary><Table label="Response chart data"><thead><tr>{headings.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{chartRows.map(row => <tr key={row[0]}>{row.map((v, i) => <td key={i}>{v}</td>)}</tr>)}</tbody></Table></details></Panel>
    <Panel title="Alert & Service Usage"><label>Period<select value={range} onChange={e => setRange(e.target.value)}><option value="7">Last 7 sample days</option><option value="14">Last 14 sample days</option></select></label><label>Resident Group<select value={group} onChange={e => setGroup(e.target.value)}>{['All Resident Groups', 'East Wing', 'West Wing'].map(g => <option key={g}>{g}</option>)}</select></label><p className="pp-muted">Filters update response metrics, charts, alert counts and exported data. Header search filters staff performance.</p><svg className="pp-chart" viewBox="0 0 330 250" role="img" aria-label={usage.map(u => `${u.type}: ${u.count}`).join(', ')}><line x1="25" x2="315" y1="180" y2="180" stroke="#a8bbae" />{usage.map((u, i) => <g key={u.type}><rect x={40 + i * 70} y={180 - u.count * 120 / Math.max(...usage.map(v => v.count), 1)} width="36" height={u.count * 120 / Math.max(...usage.map(v => v.count), 1)} fill={['#ef5757', '#f29900', '#e6bc00', '#49a1e7'][i]} rx="3" /><text x={58 + i * 70} y={170 - u.count * 120 / Math.max(...usage.map(v => v.count), 1)} textAnchor="middle">{u.count}</text><text x={58 + i * 70} y="205" textAnchor="middle" transform={`rotate(-30 ${58 + i * 70} 205)`}>{u.type}</text></g>)}</svg><h3>Daily Alert Volume</h3><svg className="pp-chart" viewBox="0 0 330 180" role="img" aria-label={days.map(d => `${d.day}: ${d.count}`).join(', ')}><polygon points={`25,140 ${days.map((d, i) => `${25 + i * 280 / (days.length - 1)},${140 - d.count * 10}`).join(' ')} 305,140`} fill="#b5dcbc" /><polyline points={days.map((d, i) => `${25 + i * 280 / (days.length - 1)},${140 - d.count * 10}`).join(' ')} fill="none" stroke="#399747" strokeWidth="2" />{days.map((d, i) => <text key={d.day} x={25 + i * 280 / (days.length - 1)} y={130 - d.count * 10} textAnchor="middle">{d.count}</text>)}<text x="25" y="165">{lastDays[0]}</text><text x="305" y="165" textAnchor="end">{lastDays.at(-1)}</text></svg><p className="pp-muted">{selected.length} sample alerts in selected period.</p></Panel></div>
    <Panel title="Staff Performance" actions={<button className="sd-primary" onClick={() => csvDownload('communitycare-demo-staff-performance.csv', [staffHeadings, ...staffRows])}>Download Staff CSV</button>}><div className="pp-performance"><Table label="Staff performance"><thead><tr>{['Staff Name', 'Tasks Completed¹', 'Alerts Responded²', 'Avg Response²', 'Attendance¹'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{staff.map(s => <tr key={s.name}><th>{s.name}</th><td>{s.tasks}</td><td>{s.alerts}</td><td>{s.response}</td><td>{s.attendance}%</td></tr>)}{!staff.length && <tr><td colSpan={5}>No staff match your search.</td></tr>}</tbody></Table><div className="pp-bars"><strong>Monthly Tasks Completed</strong>{staff.map(s => <div key={s.name}><span>{s.name} · {s.tasks}</span><i style={{ width: `${s.tasks / 180 * 100}%` }} /></div>)}<span>Scale: 0–180 tasks</span></div></div><p className="pp-muted">¹ Fixed sample month. ² Selected period and resident group. Historical sample dataset; new live-preview alerts do not alter historical analytics.</p></Panel>
  </div>
}
