import { useState } from 'react'
import { usePortal } from './PortalContext'
import { Badge, csvDownload, includesSearch, Modal, Notice, Panel, Table } from './PortalUI'

const plans = [{ name: 'Standard', price: '$199', limit: '100 residents', support: 'Email only', advanced: 'No' }, { name: 'Premium', price: '$499', limit: '500 residents', support: '24/7 priority', advanced: 'Yes' }, { name: 'Enterprise', price: 'Custom', limit: 'Unlimited', support: 'Dedicated agent', advanced: 'Yes' }]
const invoices = ['09', '08', '07', '06'].map(month => ({ id: `INV-2026-${month}`, date: `2026-${month}-15`, amount: '499.00', status: 'Paid' }))
export default function SubscriptionPage() {
  const { search, print } = usePortal()
  const [plan, setPlan] = useState('Premium')
  const [methods, setMethods] = useState([{ id: 'card', label: 'Demo Visa •••• 4242', detail: 'Sample card · No real credentials', primary: true }, { id: 'bank', label: 'Demo Checking •••• 9876', detail: 'Sample bank account', primary: false }])
  const [modal, setModal] = useState<{ kind: string; value?: string } | null>(null)
  const [notice, setNotice] = useState('')
  const current = plans.find(p => p.name === plan)!
  const visible = invoices.filter(i => includesSearch(search, i.id, i.date, i.amount, i.status))
  function download(id?: string) { const selected = visible.filter(i => !id || i.id === id); csvDownload('communitycare-demo-invoices.csv', [['Invoice', 'Date', 'Amount USD', 'Status'], ...selected.map(i => [i.id, i.date, i.amount, i.status])]); setNotice(`Exported ${selected.length} sample invoice records as CSV.`) }
  return <div className="pp-main"><Notice>{notice}</Notice><div className="pp-plan-layout"><Panel title="Current Plan" className="pp-plan" actions={<Badge value="Active" />}><h3>{plan} Plan</h3><p className="pp-price">{current.price}<small>{plan === 'Enterprise' ? ' quote' : ' USD / month'}</small></p><ul className="pp-features"><li>{current.limit}</li><li>{current.support}</li><li>{current.advanced === 'Yes' ? 'Advanced reporting' : 'Basic reporting'}</li><li>Staff management</li></ul><p className="pp-muted">Sample renewal: 15 October 2026</p><button className="sd-primary" onClick={() => setModal({ kind: 'features' })}>View All Features</button></Panel><Panel title="Manage Payment Methods"><p className="pp-muted">Demo methods only. No card numbers, banking details or real payments are collected.</p><div className="pp-methods">{methods.map(m => <article className="pp-method" key={m.id}><strong>{m.label}</strong><small>{m.detail}</small>{m.primary && <Badge value="Default" />}<div className="pp-actions"><button disabled={m.primary} onClick={() => { setMethods(list => list.map(item => ({ ...item, primary: item.id === m.id }))); setNotice('Demo default method updated.') }}>Set default</button><button aria-label={`Remove ${m.label}`} onClick={() => setModal({ kind: 'remove', value: m.id })}>Remove</button></div></article>)}{!methods.length && <p>No demo payment methods. Add a sample method to preview the layout.</p>}</div><button className="sd-primary" onClick={() => setModal({ kind: 'add' })}>＋ Add Demo Payment Method</button></Panel></div>
    <Panel title="Manage Your Plan"><Table label="Plan comparison"><thead><tr><th>Feature</th>{plans.map(p => <th key={p.name} className={p.name === plan ? 'pp-current' : ''}>{p.name}{p.name === plan ? ' (Current)' : ''}</th>)}</tr></thead><tbody>{[['Price (USD/month)', ...plans.map(p => p.price)], ['User limit', ...plans.map(p => p.limit)], ['Support level', ...plans.map(p => p.support)], ['Advanced reporting', ...plans.map(p => p.advanced)]].map(row => <tr key={row[0]}><th>{row[0]}</th>{row.slice(1).map((v, i) => <td className={plans[i].name === plan ? 'pp-current' : ''} key={i}>{v}</td>)}</tr>)}<tr><th>Preview plan</th>{plans.map(p => <td key={p.name}><button disabled={p.name === plan} onClick={() => setModal({ kind: 'plan', value: p.name })}>{p.name === plan ? 'Current Plan' : `Preview ${p.name}`}</button></td>)}</tr></tbody></Table><p className="pp-muted">Plan changes affect this preview only. No charge, renewal or entitlement change occurs.</p></Panel>
    <Panel title="Billing History" actions={<><button onClick={() => download()}>Download Filtered CSV</button><button onClick={() => print({ title: 'Sample Billing History', headings: ['Invoice', 'Date', 'USD', 'Status'], rows: visible.map(i => [i.id, i.date, i.amount, i.status]) })}>Print / Save PDF</button></>}><Table label="Billing history"><thead><tr>{['Invoice ID', 'Date', 'Amount (USD)', 'Status', 'Action'].map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{visible.map(i => <tr key={i.id}><th>{i.id}</th><td>{i.date}</td><td>${i.amount}</td><td><Badge value={i.status} /></td><td><button aria-label={`Download ${i.id}`} onClick={() => download(i.id)}>Download CSV</button></td></tr>)}{!visible.length && <tr><td colSpan={5}>No invoices match your search.</td></tr>}</tbody></Table></Panel>
    {modal && <Modal title={modal.kind === 'plan' ? 'Preview Plan Change' : modal.kind === 'add' ? 'Add Demo Method' : modal.kind === 'remove' ? 'Remove Demo Method?' : `${plan} Features`} onClose={() => setModal(null)}>
      {modal.kind === 'features' ? <><ul className="pp-features"><li>{current.limit}</li><li>{current.support}</li><li>Advanced reporting: {current.advanced}</li></ul><button onClick={() => setModal(null)}>Close</button></> : <><p>{modal.kind === 'plan' ? `Switch the displayed demo plan to ${modal.value}? This does not purchase a subscription.` : modal.kind === 'add' ? 'Add a prefilled sample payment method. Do not enter any real payment information.' : 'Remove this sample method? Another remaining method will become default if needed.'}</p><div className="sd-dialog-actions"><button onClick={() => setModal(null)}>Cancel</button><button className="sd-primary" onClick={() => { if (modal.kind === 'plan') { setPlan(modal.value!); setNotice('Demo plan updated. No payment was made.') } else if (modal.kind === 'add') { setMethods(list => [...list, { id: crypto.randomUUID(), label: 'Demo Mastercard •••• 5555', detail: 'Sample method · Not chargeable', primary: list.length === 0 }]); setNotice('Sample payment method added.') } else { setMethods(list => { const next = list.filter(m => m.id !== modal.value); return next.some(m => m.primary) ? next : next.map((m, i) => ({ ...m, primary: i === 0 })) }); setNotice('Sample method removed.') } setModal(null) }}>{modal.kind === 'plan' ? 'Apply demo plan' : modal.kind === 'add' ? 'Add sample method' : 'Remove sample method'}</button></div></>}
    </Modal>}
  </div>
}
