require('dotenv').config();
const http=require('http');
const {Server}=require('socket.io');
const {createGateway}=require('./config/supabase');
const {createApp}=require('./app');
const {attachAlerts}=require('./sockets/alerts');
const db=createGateway(process.env);
const origins=(process.env.ALLOWED_ORIGINS??'').split(',').map(s=>s.trim()).filter(Boolean);
if(!origins.length) throw new Error('Set ALLOWED_ORIGINS in backend/.env');
const server=http.createServer(createApp(db,process.env));
const io=new Server(server,{cors:{origin:origins},allowRequest(req,callback){callback(null,!req.headers.origin||origins.includes(req.headers.origin));}});
attachAlerts(io,db);
server.listen(Number(process.env.PORT||5000),()=>console.log(`CommunityCare Express listening on port ${process.env.PORT||5000}`));
