import { useState } from 'react'
import type { FormEvent } from 'react'
import { featureNames, useAdmin } from './AdminContext'
import type { Plan } from './AdminContext'
import { Badge, matches, Modal, Notice, Panel, Table, Toggle } from './AdminUI'

function Features({ plan }: { plan: Plan }) {
  const { update } = useAdmin(); const [draft, setDraft] = useState({ ...plan.features }); const [notice, setNotice] = useState('')
  return <><div className="ad-features">{featureNames.map(name => <Toggle key={name} label={name} checked={draft[name]} onChange={value => setDraft({ ...draft, [name]: value })} />)}</div><button className="ad-primary" onClick={() => { update('Plan Features', `Updated features for ${plan.name}.`, old => ({ ...old, plans: old.plans.map(p => p.id === plan.id ? { ...p, features: draft } : p) })); setNotice('Demo plan features saved; no live entitlement changes.') }}>Save Configuration</button><Notice>{notice}</Notice></>
}
export default function AdminSubscriptionsPage() {
  const { state, update, search, print } = useAdmin()
  const [selectedPlan, setSelectedPlan] = useState('PLAN-1')
  const [paymentId, setPaymentId] = useState('TXN-8924')
  const [tab, setTab] = useState('Payments')
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  const [modal, setModal] = useState<{ kind: string; id?: string; status?: string } | null>(null)
  const plan = state.plans.find(p => p.id === selectedPlan) || state.plans[0]
  const payment = state.payments.find(p => p.id === paymentId)!
  const editingPlan = state.plans.find(p => p.id === modal?.id)
  const nameOf = (id: string) => state.properties.find(p => p.id === id)?.name || id
  function open(kind: string, id?: string, status?: string) { setError(''); setModal({ kind, id, status }) }
  function savePlan(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const d = new FormData(e.currentTarget); const name = String(d.get('name') || '').trim(); const price = Number(d.get('price'))
    if (!name || !Number.isFinite(price) || price < 0 || price > 1000000) { setError('Enter a name and price between 0 and 1,000,000 USD.'); return }
    if (state.plans.some(p => p.id !== editingPlan?.id && p.name.toLowerCase() === name.toLowerCase())) { setError('A plan with that name already exists.'); return }
    const next: Plan = { id: editingPlan?.id || `PLAN-${crypto.randomUUID().slice(0, 6)}`, name, price: Math.round(price * 100) / 100, duration: String(d.get('duration')), active: editingPlan?.active ?? true, features: editingPlan?.features || Object.fromEntries(featureNames.map(f => [f, false])) }
    update(editingPlan ? 'Plan Update' : 'Plan Create', `Saved demo plan ${name}.`, old => ({ ...old, plans: editingPlan ? old.plans.map(p => p.id === next.id ? next : p) : [...old.plans, next] })); setSelectedPlan(next.id); setModal(null); setNotice('Plan saved in preview. Existing transaction amounts are unchanged.')
  }
  return <div className="ad-main"><Notice>{notice}</Notice><Panel title="Define Subscription Plans" actions={<button className="ad-primary" onClick={() => open('plan')}>＋ Create New Plan</button>}><Table label="Subscription plans"><thead><tr>{['Plan Name', 'Price (USD)', 'Duration', 'Status', 'Actions'].map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{state.plans.filter(p => matches(search, p.name, p.duration)).map(p => <tr key={p.id}><th>{p.name}</th><td>${p.price.toFixed(2)}</td><td>{p.duration}</td><td><Badge value={p.active ? 'Active' : 'Inactive'} /></td><td><div className="ad-actions"><button aria-label={`Edit ${p.name}`} onClick={() => open('plan', p.id)}>Edit</button><button disabled={p.active && state.properties.some(property => property.status !== 'Archived' && property.settings.plan === p.id)} title="Assigned plans cannot be deactivated until properties are moved to another plan." onClick={() => { update('Plan Status', `${p.name} ${p.active ? 'deactivated' : 'activated'}.`, old => ({ ...old, plans: old.plans.map(item => item.id === p.id ? { ...item, active: !item.active } : item) })); setNotice('Demo plan status updated.') }}>{p.active ? 'Deactivate' : 'Activate'}</button></div></td></tr>)}</tbody></Table><p className="ad-muted">Plans assigned to non-archived properties cannot be deactivated. Prices are illustrative USD amounts.</p></Panel>
    <div className="ad-narrow-grid"><Panel title="Configure Features"><label>Selected Plan<select value={plan.id} onChange={e => setSelectedPlan(e.target.value)}>{state.plans.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><Features key={plan.id} plan={plan} /></Panel><Panel title="Financial Hub"><div className="ad-tabs">{['Payments', 'Invoices'].map(t => <button key={t} aria-pressed={t === tab} onClick={() => setTab(t)}>{t}</button>)}</div><Table label="Financial records"><thead><tr><th>Select</th><th>{tab === 'Payments' ? 'Transaction ID' : 'Invoice Reference'}</th><th>Property</th><th>Plan</th><th>Amount (USD)</th><th>Date</th><th>Status</th></tr></thead><tbody>{state.payments.filter(p => matches(search, p.id, nameOf(p.property), state.plans.find(plan => plan.id === p.plan)?.name || '', p.status)).map(p => <tr className={p.id === paymentId ? 'ad-selected' : ''} key={p.id}><td><input type="radio" name="admin-payment" aria-label={`Select ${p.id}`} checked={paymentId === p.id} onChange={() => setPaymentId(p.id)} /></td><th>{tab === 'Payments' ? p.id : `INV-${p.id.slice(4)}`}</th><td>{nameOf(p.property)}</td><td>{state.plans.find(plan => plan.id === p.plan)?.name}</td><td>${p.amount.toFixed(2)}</td><td>{p.date}</td><td><Badge value={p.status} /></td></tr>)}</tbody></Table><p className="ad-muted">Selected: {payment.id} · {nameOf(payment.property)}. These are sample transactions; no payment service is connected.</p><div className="ad-actions"><button className="ad-primary" disabled={payment.status === 'Paid'} onClick={() => open('payment', payment.id)}>Simulate Payment</button><button onClick={() => { print({ title: `Sample Invoice INV-${payment.id.slice(4)}`, headers: ['Property', 'Plan', 'Amount USD', 'Date', 'Status'], rows: [[nameOf(payment.property), state.plans.find(p => p.id === payment.plan)?.name || '', payment.amount.toFixed(2), payment.date, payment.status]], note: 'Not a tax invoice or payment request.' }); update('Invoice Preview', `Prepared sample invoice for ${payment.id}.`) }}>Print / Save Invoice PDF</button></div></Panel></div>
    <div className="ad-grid"><Panel title="Promotions & Trials" actions={<button onClick={() => open('promo')}>＋ New</button>}><Table label="Promotion campaigns"><thead><tr><th>Campaign</th><th>Discount</th><th>Status</th><th>Action</th></tr></thead><tbody>{state.promos.map(p => <tr key={p.id}><th>{p.name}</th><td>{p.discount}%</td><td><Badge value={p.active ? 'Active' : 'Inactive'} /></td><td><button onClick={() => update('Promotion Status', `Toggled campaign ${p.name}.`, old => ({ ...old, promos: old.promos.map(item => item.id === p.id ? { ...item, active: !item.active } : item) }))}>{p.active ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></Table><p className="ad-muted">Campaign previews do not alter invoices or charge amounts.</p></Panel><Panel title="Refund Requests"><Table label="Refund requests"><thead><tr><th>Property</th><th>Amount (USD)</th><th>Status</th><th>Actions</th></tr></thead><tbody>{state.refunds.map(r => <tr key={r.id}><th>{nameOf(r.property)}</th><td>${r.amount.toFixed(2)}</td><td><Badge value={r.status} /></td><td>{r.status === 'Pending' ? <div className="ad-actions"><button onClick={() => open('refund', r.id, 'Approved')}>Approve Demo Refund</button><button onClick={() => open('refund', r.id, 'Declined')}>Decline</button></div> : 'Reviewed'}</td></tr>)}</tbody></Table></Panel></div>
    {modal && <Modal title={modal.kind === 'plan' ? editingPlan ? 'Edit Plan' : 'Create Plan' : modal.kind === 'promo' ? 'New Promotion' : modal.kind === 'payment' ? 'Simulate Payment?' : 'Review Demo Refund'} onClose={() => setModal(null)}>{modal.kind === 'plan' ? <form onSubmit={savePlan}><label>Plan Name<input name="name" required maxLength={100} defaultValue={editingPlan?.name} /></label><label>Price (USD)<input name="price" type="number" required min="0" max="1000000" step="0.01" defaultValue={editingPlan?.price} /></label><label>Duration<select name="duration" defaultValue={editingPlan?.duration || 'Monthly'}><option>Monthly</option><option>Yearly</option></select></label>{error && <p role="alert" className="ad-error">{error}</p>}<div className="ad-actions ad-end"><button type="button" onClick={() => setModal(null)}>Cancel</button><button className="ad-primary">Save Plan</button></div></form> : modal.kind === 'promo' ? <form onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); const name = String(d.get('name') || '').trim(); if (!name) { setError('Enter a campaign name.'); return }; update('Promotion Create', `Created campaign ${name}.`, old => ({ ...old, promos: [...old.promos, { id: crypto.randomUUID(), name, discount: Number(d.get('discount')), active: true }] })); setModal(null) }}><label>Campaign Name<input name="name" required maxLength={100} /></label><label>Discount (%)<input type="number" name="discount" min="1" max="100" step="1" required /></label>{error && <p className="ad-error">{error}</p>}<button className="ad-primary">Create Demo Campaign</button></form> : <><p>{modal.kind === 'payment' ? 'Mark the selected sample transaction as paid? This is a local simulation; no money will be charged.' : `Mark this sample refund as ${modal.status}? No refund will be issued and no bank account will be contacted.`}</p><div className="ad-actions ad-end"><button onClick={() => setModal(null)}>Cancel</button><button className="ad-primary" onClick={() => { if (modal.kind === 'payment') update('Payment Simulation', `Marked ${modal.id} paid in demo.`, old => ({ ...old, payments: old.payments.map(p => p.id === modal.id ? { ...p, status: 'Paid' } : p) })); else update('Refund Review', `Marked ${modal.id} ${modal.status} in demo.`, old => ({ ...old, refunds: old.refunds.map(r => r.id === modal.id ? { ...r, status: modal.status! } : r) })); setNotice('Demo financial status updated and logged. No money moved.'); setModal(null) }}>Confirm Simulation</button></div></>}</Modal>}
  </div>
}
