import { useState } from 'react'
import { DEMO_NOW, useAdmin } from './AdminContext'
import type { Audit } from './AdminContext'
import { Badge, csvDownload, matches, Modal, Notice, Panel, Table, Toggle } from './AdminUI'

export default function AuditLogsPage() {
  const { state, update, search, print } = useAdmin()
  const [draft, setDraft] = useState({ user: '', action: 'All Actions', range: '24' })
  const [filter, setFilter] = useState(draft)
  const [page, setPage] = useState(1)
  const [format, setFormat] = useState('CSV')
  const [exportDate, setExportDate] = useState('')
  const [notice, setNotice] = useState('')
  const [detail, setDetail] = useState<Audit | null>(null)
  const [retention, setRetention] = useState(state.retention)
  const [security, setSecurity] = useState([{ id: 'SEC-102', type: 'Multiple failed logins', time: '2026-10-06 14:50', status: 'Active' }, { id: 'SEC-101', type: 'Unusual IP access', time: '2026-10-06 13:00', status: 'Investigating' }, { id: 'SEC-100', type: 'Privilege escalation', time: '2026-10-05 10:00', status: 'Resolved' }])
  const cutoff = new Date(DEMO_NOW).getTime() - Number(filter.range) * 3600000
  const logs = state.logs.filter(l => matches(search, l.id, l.user, l.action, l.description, l.result) && matches(filter.user, l.user) && (filter.action === 'All Actions' || l.action === filter.action) && (filter.range === 'all' || new Date(l.time).getTime() >= cutoff))
  const totalPages = Math.max(1, Math.ceil(logs.length / 5)); const currentPage = Math.min(page, totalPages); const visible = logs.slice((currentPage - 1) * 5, currentPage * 5)
  function exportLogs() {
    const selected = logs.filter(l => !exportDate || l.time.startsWith(exportDate)); const headers = ['Log ID', 'Time', 'User', 'Action', 'Description', 'Result']; const rows = selected.map(l => [l.id, l.time, l.user, l.action, l.description, l.result])
    if (format === 'CSV') csvDownload('admin-demo-audit-logs.csv', [headers, ...rows]); else print({ title: 'Audit Log Export', headers, rows, note: 'Filtered snapshot before recording this export action.' })
    update('Data Export', `Prepared ${selected.length} demo audit records as ${format}.`); setNotice(`Prepared ${selected.length} matching records. Exports include all matching pages, not only this page.`)
  }
  return <div className="ad-main"><Notice>{notice}</Notice><div className="ad-wide-grid"><Panel title="User Action Tracking"><form onSubmit={e => { e.preventDefault(); setFilter(draft); setPage(1) }}><div className="ad-filter"><label>User Name<input value={draft.user} onChange={e => setDraft({ ...draft, user: e.target.value })} placeholder="Search user..." /></label><label>Action Type<select value={draft.action} onChange={e => setDraft({ ...draft, action: e.target.value })}><option>All Actions</option>{[...new Set(state.logs.map(l => l.action))].sort().map(action => <option key={action}>{action}</option>)}</select></label><label>Date Range<select value={draft.range} onChange={e => setDraft({ ...draft, range: e.target.value })}><option value="24">Last 24 sample hours</option><option value="168">Last 7 sample days</option><option value="all">All sample dates</option></select></label></div><div className="ad-actions"><button className="ad-primary">Apply Filter</button><button type="button" onClick={() => { const initial = { user: '', action: 'All Actions', range: '24' }; setDraft(initial); setFilter(initial); setPage(1) }}>Reset Filters</button></div></form><p className="ad-muted">Sample clock: 6 October 2026, 15:00. Newly saved Admin changes are added to this local audit list.</p></Panel><Panel title="Export Audit Logs"><label>Export Format<select value={format} onChange={e => setFormat(e.target.value)}><option>CSV</option><option>PDF</option></select></label><label>Export Date (optional)<input type="date" value={exportDate} onChange={e => setExportDate(e.target.value)} /></label><button onClick={exportLogs}>Export Filtered Logs</button><p className="ad-muted">PDF opens browser Print / Save as PDF. Optional date further narrows the export.</p></Panel></div>
    <Panel title="System Change History" actions={<button onClick={() => { setPage(1); setNotice('Showing the latest in-memory demo records. No server connection is configured.') }}>↻ Refresh</button>}><Table label="System audit logs"><thead><tr>{['Log ID', 'Timestamp', 'User', 'Action Type', 'Description', 'Result', 'Actions'].map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{visible.map(l => <tr key={l.id}><th>{l.id}</th><td>{l.time.replace('T', ' ')}</td><td>{l.user}</td><td>{l.action}</td><td>{l.description}</td><td><Badge value={l.result} /></td><td><button aria-label={`View ${l.id}`} onClick={() => setDetail(l)}>View</button></td></tr>)}{!visible.length && <tr><td colSpan={7}>No audit records match your filters.</td></tr>}</tbody></Table><div className="ad-pagination"><span>{logs.length} records · Page {currentPage} / {totalPages}</span><button disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>Prev</button><button disabled={currentPage === totalPages} onClick={() => setPage(currentPage + 1)}>Next</button></div></Panel>
    <div className="ad-grid"><div id="ad-security"><Panel title="Security Alerts" className="ad-warning"><Table label="Security alert samples"><thead><tr><th>ID</th><th>Type</th><th>Sample Time</th><th>Status</th></tr></thead><tbody>{security.map(s => <tr key={s.id}><th>{s.id}</th><td>{s.type}</td><td>{s.time}</td><td><select aria-label={`Status ${s.id}`} value={s.status} onChange={e => { const status = e.target.value; setSecurity(list => list.map(item => item.id === s.id ? { ...item, status } : item)); update('Security Review', `${s.id} marked ${status} in demo.`) }}>{['Active', 'Investigating', 'Resolved'].map(status => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></Table><p className="ad-muted">Illustrative alerts only; this preview is not monitoring real sign-ins or threats.</p></Panel></div><Panel title="Log Retention Settings"><p>Preview a retention policy for future backend integration.</p><label>Retention Period<select value={retention.days} onChange={e => setRetention({ ...retention, days: e.target.value })}><option value="30">30 Days</option><option value="90">90 Days</option><option value="365">365 Days</option></select></label><Toggle label="Automatic Purge (preview only)" checked={retention.purge} onChange={purge => setRetention({ ...retention, purge })} /><p className="ad-muted">Saving this setting never deletes records in this demo. Server retention and deletion are not implemented.</p><button className="ad-primary" onClick={() => { update('Retention Settings', `Saved demo retention: ${retention.days} days; purge ${retention.purge ? 'enabled' : 'disabled'} (not executed).`, old => ({ ...old, retention: { ...retention } })); setNotice('Retention preview saved. No records were deleted.') }}>Save Settings</button></Panel></div>
    {detail && <Modal title={`Audit Record ${detail.id}`} onClose={() => setDetail(null)}><dl className="ad-detail">{Object.entries({ Time: detail.time, User: detail.user, Action: detail.action, Description: detail.description, Result: detail.result, 'Sample IP': detail.ip }).map(([label, value]) => <div key={label} style={{ display: 'contents' }}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="ad-muted">IP addresses use documentation ranges and do not identify real users.</p><button onClick={() => setDetail(null)}>Close</button></Modal>}
  </div>
}
