import { useState } from 'react'
import type { FormEvent } from 'react'
import { useAdmin } from './AdminContext'
import type { Property } from './AdminContext'
import { Badge, BarChart, csvDownload, LineChart, matches, Modal, Notice, Panel, Table, Toggle } from './AdminUI'

const blank = { name: '', address: '', units: '1', manager: '', activation: '2026-10-06' }
function Settings({ property }: { property: Property }) {
  const { state, update } = useAdmin()
  const [draft, setDraft] = useState(property.settings)
  const [notice, setNotice] = useState('')
  return <Panel title={`Configure Property Settings · ${property.name}`}><Notice>{notice}</Notice><form onSubmit={e => { e.preventDefault(); update('Property Settings', `Updated settings for ${property.name}.`, old => ({ ...old, properties: old.properties.map(p => p.id === property.id ? { ...p, settings: { ...draft } } : p) })); setNotice('Property settings saved in this preview only.') }}><div className="ad-field-grid"><Toggle label="Emergency Response" checked={draft.emergency} onChange={value => setDraft({ ...draft, emergency: value })} /><label>Subscription Plan<select value={draft.plan} onChange={e => setDraft({ ...draft, plan: e.target.value })}>{state.plans.filter(p => p.active || p.id === draft.plan).map(p => <option key={p.id} value={p.id} disabled={!p.active}>{p.name}{!p.active ? ' (inactive)' : ''}</option>)}</select></label><label>Check-In Time<input type="time" required value={draft.checkIn} onChange={e => setDraft({ ...draft, checkIn: e.target.value })} /></label><label>Maintenance Schedule<input type="date" value={draft.maintenance} onChange={e => setDraft({ ...draft, maintenance: e.target.value })} /></label></div><div className="ad-actions"><button className="ad-primary" disabled={property.status === 'Archived'}>Save Settings</button><button type="button" onClick={() => { setDraft({ emergency: true, checkIn: '10:00', plan: state.plans.find(p => p.active)?.id || draft.plan, maintenance: '' }); setNotice('Default values loaded. Save Settings to apply.') }}>Reset to Default</button></div></form><p className="ad-muted">These settings do not control actual devices, subscriptions or notifications.</p></Panel>
}
export default function PropertiesPage() {
  const { state, update, search, navigate } = useAdmin()
  const [draft, setDraft] = useState(blank)
  const [editing, setEditing] = useState('')
  const [selectedId, setSelectedId] = useState('PRP-1042')
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  const [archive, setArchive] = useState(false)
  const selected = state.properties.find(p => p.id === selectedId) || state.properties[0]
  function reset() { setDraft(blank); setEditing(''); setError(''); document.getElementById('ad-property-name')?.focus() }
  function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const units = Number(draft.units)
    if (!draft.name.trim() || !draft.address.trim() || !Number.isInteger(units) || units < 1 || units > 100000) { setError('Enter a property name, address and whole-number unit count from 1 to 100,000.'); return }
    if (state.properties.some(p => p.id !== editing && p.name.toLowerCase() === draft.name.trim().toLowerCase())) { setError('A property with this name already exists.'); return }
    const old = state.properties.find(p => p.id === editing)
    const item: Property = { id: old?.id || `PRP-${crypto.randomUUID().slice(0, 6).toUpperCase()}`, name: draft.name.trim(), address: draft.address.trim(), manager: draft.manager.trim(), activation: draft.activation, units, status: old?.status || 'Active', residents: old?.residents || 0, alerts: old?.alerts || 0, response: old?.response || 0, usage: old?.usage || 0, settings: old?.settings || { emergency: true, checkIn: '10:00', plan: state.plans.find(p => p.active)?.id || '', maintenance: '' } }
    update(editing ? 'Property Update' : 'Property Create', `${editing ? 'Updated' : 'Registered'} ${item.name}.`, store => ({ ...store, properties: editing ? store.properties.map(p => p.id === editing ? item : p) : [...store.properties, item] }))
    setSelectedId(item.id); setNotice(`${item.name} saved. Dashboard counts and Audit Logs updated.`); reset()
  }
  return <div className="ad-main"><Notice>{notice}</Notice><Panel title={editing ? 'Edit Property' : 'Register New Condominium Property'} actions={<button className="ad-primary" id="ad-new-property" onClick={reset}>＋ New Property</button>}><form onSubmit={submit}><div className="ad-field-grid"><label>Property Name<input id="ad-property-name" required maxLength={100} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="e.g. Oceanview Condos" /></label><label>Address<input required maxLength={250} value={draft.address} onChange={e => setDraft({ ...draft, address: e.target.value })} /></label><label>Number of Units<input type="number" min="1" max="100000" step="1" required value={draft.units} onChange={e => setDraft({ ...draft, units: e.target.value })} /></label><label>Manager Contact Email<input type="email" required maxLength={150} value={draft.manager} onChange={e => setDraft({ ...draft, manager: e.target.value })} /></label><label>Activation Date<input type="date" required value={draft.activation} onChange={e => setDraft({ ...draft, activation: e.target.value })} /></label></div>{error && <p role="alert" className="ad-error">{error}</p>}<div className="ad-actions"><button className="ad-primary">Save Property</button><button type="button" onClick={reset}>Cancel</button></div></form><Table label="Property registry"><thead><tr>{['Property ID', 'Name', 'Location', 'Status', 'Actions'].map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{state.properties.filter(p => matches(search, p.id, p.name, p.address, p.status)).map(p => <tr key={p.id} className={selected.id === p.id ? 'ad-selected' : ''}><th>{p.id}</th><td>{p.name}</td><td>{p.address}</td><td><Badge value={p.status} /></td><td><div className="ad-actions"><button aria-label={`Select ${p.name}`} onClick={() => setSelectedId(p.id)}>Select</button><button aria-label={`Edit ${p.name}`} onClick={() => { setSelectedId(p.id); setEditing(p.id); setDraft({ name: p.name, address: p.address, units: String(p.units), manager: p.manager, activation: p.activation }); document.getElementById('ad-property-name')?.focus() }}>Edit</button></div></td></tr>)}</tbody></Table><p className="ad-muted">Select a row to configure or monitor that property below.</p></Panel>
    <Settings key={selected.id} property={selected} />
    <Panel title={`Property Monitoring · ${selected.name}`}><div className="ad-kpis"><div className="ad-kpi">Total Residents<strong>{selected.residents}</strong></div><div className="ad-kpi">Active Alerts<strong>{selected.alerts}</strong></div><div className="ad-kpi">Average Response<strong>{selected.response ? `${selected.response}m` : 'No data'}</strong></div><div className="ad-kpi">Usage Rate<strong>{selected.usage}%</strong></div></div><div className="ad-grid" style={{ marginTop: 20 }}><LineChart labels={['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct']} series={[{ name: 'Illustrative usage trend', color: '#3f9950', values: [0.6, 0.7, 0.77, 0.84, 0.9, 1].map(v => Math.round(selected.usage * v)) }]} unit="Usage (%)" /><BarChart labels={['Pending', 'Resolved']} values={[selected.alerts, 0]} colors={['#f19317', '#7caf98']} unit="Current sample alert status" /></div><p className="ad-muted">Usage trend is illustrative, not measured historical device usage. New properties begin with no monitoring data.</p><button onClick={() => navigate('analytics')}>View Detailed Analytics</button></Panel>
    <Panel title={`Decommission Property · ${selected.name}`} className="ad-warning"><p>Archive this demo property without deleting its records. Archived properties are excluded from Dashboard totals and can be restored.</p><div className="ad-actions"><button className={selected.status === 'Archived' ? 'ad-primary' : 'ad-danger'} onClick={() => setArchive(true)}>{selected.status === 'Archived' ? 'Restore Property' : 'Initiate Decommission'}</button><button onClick={() => { csvDownload('demo-property-record.csv', [['ID', 'Name', 'Address', 'Units', 'Status'], [selected.id, selected.name, selected.address, selected.units, selected.status]]); update('Data Export', `Exported sample property ${selected.name}.`); setNotice('Property summary exported as CSV; no server archive was created.') }}>Export Property Data</button></div></Panel>
    {archive && <Modal title={selected.status === 'Archived' ? 'Restore Demo Property?' : 'Archive Demo Property?'} onClose={() => setArchive(false)}><p>{selected.name}: this only changes its local preview status. No files, accounts or historical records will be deleted.</p><div className="ad-actions ad-end"><button onClick={() => setArchive(false)}>Cancel</button><button className="ad-primary" onClick={() => { const status = selected.status === 'Archived' ? 'Active' : 'Archived'; update('Property Status', `${selected.name} changed to ${status}.`, old => ({ ...old, properties: old.properties.map(p => p.id === selected.id ? { ...p, status } : p) })); setNotice(`${selected.name}: ${status}.`); setArchive(false) }}>Confirm demo change</button></div></Modal>}
  </div>
}
