import { useState } from 'react'
import type { FormEvent } from 'react'
import { defaultConfig, useAdmin } from './AdminContext'
import type { Config } from './AdminContext'
import { Notice, Panel, Toggle } from './AdminUI'

export default function SystemConfigurationPage() {
  const { state, update } = useAdmin()
  const [draft, setDraft] = useState<Config>({ ...state.config, contacts: [...state.config.contacts] })
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  const dirty = JSON.stringify(draft) !== JSON.stringify(state.config)
  function save(e: FormEvent<HTMLFormElement>) {
    e.preventDefault()
    if (!draft.wake.trim()) { setError('Enter a wake word.'); return }
    if (![draft.volume, draft.escalation, draft.impact, draft.confirmation, draft.noMovement].every(Number.isFinite)) { setError('Enter valid numeric settings.'); return }
    if (!Number.isInteger(draft.escalation) || draft.escalation < 1 || draft.escalation > 300 || draft.impact < 0.1 || draft.impact > 10 || draft.confirmation < 1 || draft.confirmation > 120 || draft.noMovement < 5 || draft.noMovement > 600) { setError('Settings must stay within the displayed demo ranges.'); return }
    update('Config Update', 'Saved demo voice, emergency and fall-detection settings.', old => ({ ...old, config: { ...draft, wake: draft.wake.trim(), contacts: [...draft.contacts] } })); setDraft({ ...draft, wake: draft.wake.trim() }); setError(''); setNotice('Configuration saved in this preview and recorded in Audit Logs. No device, SMS or emergency service was contacted.')
  }
  function move(index: number, direction: number) { const contacts = [...draft.contacts]; const other = index + direction; if (other < 0 || other >= contacts.length) return; [contacts[index], contacts[other]] = [contacts[other], contacts[index]]; setDraft({ ...draft, contacts }) }
  return <form className="ad-main" onSubmit={save}><Notice>{notice}</Notice><div className="ad-heading"><div><h2>System Configuration Module</h2><p className="ad-muted">Manage the preview of global settings, emergency protocols and feature toggles.</p></div><div className="ad-actions"><button type="button" disabled={!dirty} onClick={() => { setDraft({ ...state.config, contacts: [...state.config.contacts] }); setError(''); setNotice('Unsaved changes discarded.') }}>Discard Changes</button><button className="ad-primary" disabled={!dirty}>Save Configuration</button></div></div>{error && <p className="ad-error" role="alert">{error}</p>}
    <div className="ad-narrow-grid"><Panel title="Voice Settings"><label>Wake Word<input required maxLength={50} value={draft.wake} onChange={e => setDraft({ ...draft, wake: e.target.value })} /></label><label>Language<select value={draft.language} onChange={e => setDraft({ ...draft, language: e.target.value })}><option>English</option><option>Bahasa Melayu</option><option>中文</option></select></label><label>Volume · {draft.volume}%<input aria-label="Voice volume" type="range" min="0" max="100" step="1" value={draft.volume} onChange={e => setDraft({ ...draft, volume: Number(e.target.value) })} /></label><Toggle label="Voice Confirmation" checked={draft.voice} onChange={voice => setDraft({ ...draft, voice })} /></Panel>
    <Panel title="Emergency Protocols"><div className="ad-field-grid"><div><fieldset style={{ border: 0, padding: 0, margin: '0 0 16px' }}><legend>SOS Activation Method</legend>{['Voice Only', 'Hardware Button', 'Both'].map(value => <label className="ad-inline-check" key={value}><input type="radio" name="sos-activation" checked={draft.activation === value} onChange={() => setDraft({ ...draft, activation: value })} />{value}</label>)}</fieldset><label>Escalation Time (1–300 seconds)<input type="number" required min="1" max="300" step="1" value={draft.escalation} onChange={e => setDraft({ ...draft, escalation: Number(e.target.value) })} /></label></div><div><h3>Contact Order</h3><ol className="ad-contact-list">{draft.contacts.map((contact, index) => <li key={contact}><span>{index + 1}. {contact}</span><button type="button" aria-label={`Move ${contact} up`} disabled={index === 0} onClick={() => move(index, -1)}>↑</button><button type="button" aria-label={`Move ${contact} down`} disabled={index === draft.contacts.length - 1} onClick={() => move(index, 1)}>↓</button></li>)}</ol><Toggle label="SMS Backup for Alerts" checked={draft.sms} onChange={sms => setDraft({ ...draft, sms })} /></div></div><p className="ad-muted">Contact order and timings are demonstration values, not operational emergency recommendations. No emergency number or SMS provider is configured.</p></Panel></div>
    <Panel title="Fall Detection Algorithms" className="ad-accent" actions={<Toggle label="Master Enable" checked={draft.fall} onChange={fall => setDraft({ ...draft, fall })} />}><div className="ad-four-fields"><label>Sensitivity<select disabled={!draft.fall} value={draft.sensitivity} onChange={e => setDraft({ ...draft, sensitivity: e.target.value })}><option>Low</option><option>Medium</option><option>High</option></select></label><label>Impact Threshold (0.1–10 g)<input type="number" required min="0.1" max="10" step="0.1" disabled={!draft.fall} value={draft.impact} onChange={e => setDraft({ ...draft, impact: Number(e.target.value) })} /></label><label>Confirm Timeout (1–120 s)<input type="number" required min="1" max="120" step="1" disabled={!draft.fall} value={draft.confirmation} onChange={e => setDraft({ ...draft, confirmation: Number(e.target.value) })} /></label><label>No-Movement (5–600 s)<input type="number" required min="5" max="600" step="1" disabled={!draft.fall} value={draft.noMovement} onChange={e => setDraft({ ...draft, noMovement: Number(e.target.value) })} /></label></div><Toggle label="Post-fall Voice Prompt" checked={draft.postVoice} disabled={!draft.fall} onChange={postVoice => setDraft({ ...draft, postVoice })} /><p className="ad-muted">This form does not run a fall-detection algorithm or update a mobile device.</p><button type="button" onClick={() => { setDraft({ ...defaultConfig, contacts: [...defaultConfig.contacts] }); setNotice('Default demo values loaded. Save Configuration to apply them.'); setError('') }}>Load Demo Defaults</button></Panel>
  </form>
}
