import { useState } from 'react'
import type { FormEvent } from 'react'
import { modules, roles, useAdmin } from './AdminContext'
import type { Role, User } from './AdminContext'
import { Badge, csvDownload, matches, Modal, Notice, Panel, Table, Toggle } from './AdminUI'

function Permissions({ role }: { role: Role }) {
  const { state, update } = useAdmin()
  const [draft, setDraft] = useState(() => Object.fromEntries(Object.entries(state.permissions[role]).map(([name, values]) => [name, [...values]])))
  const [notice, setNotice] = useState('')
  return <><Table label={`${role} module permissions`}><thead><tr><th>Module</th>{['View', 'Edit', 'Delete', 'Assign'].map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{modules.map(name => <tr key={name}><th>{name}</th>{draft[name].map((checked, index) => <td key={index}><input type="checkbox" aria-label={`${role} ${name} ${['View', 'Edit', 'Delete', 'Assign'][index]}`} checked={checked} disabled={role === 'System Admin'} onChange={e => { const next = [...draft[name]]; next[index] = e.target.checked; if (index === 0 && !e.target.checked) next.fill(false); if (index > 0 && e.target.checked) next[0] = true; setDraft({ ...draft, [name]: next }) }} /></td>)}</tr>)}</tbody></Table><p className="ad-muted">Edit, Delete and Assign require View. Administrator permissions are fixed in this demo. These switches do not authorize access to a real system.</p><button className="ad-primary" disabled={role === 'System Admin'} onClick={() => { update('Permission Update', `Saved ${role} demo permissions.`, old => ({ ...old, permissions: { ...old.permissions, [role]: draft } })); setNotice('Preview permissions saved; production access is unchanged.') }}>Save Permissions</button><Notice>{notice}</Notice></>
}
export default function UsersPage() {
  const { state, update, search } = useAdmin()
  const [editing, setEditing] = useState('')
  const [draft, setDraft] = useState({ name: '', email: '', role: 'Property Manager' as Role, property: 'PRP-1042' })
  const [permissionRole, setPermissionRole] = useState<Role>('Property Manager')
  const [passwordUser, setPasswordUser] = useState('USR-002')
  const [policy, setPolicy] = useState(state.forcePassword)
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  const [modal, setModal] = useState<{ kind: string; id: string } | null>(null)
  const [date, setDate] = useState('')
  const history = state.logs.filter(l => l.action === 'Login' && (!date || l.time.startsWith(date)) && matches(search, l.user, l.result))
  function reset() { setDraft({ name: '', email: '', role: 'Property Manager', property: state.properties.find(p => p.status !== 'Archived')?.id || '' }); setEditing(''); setError('') }
  function save(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); const name = draft.name.trim(); const email = draft.email.trim().toLowerCase()
    if (!name || !email) { setError('Enter a name and email address.'); return }
    if (state.users.some(u => u.id !== editing && u.email.toLowerCase() === email)) { setError('That email is already registered in this preview.'); return }
    if (draft.role !== 'System Admin' && !state.properties.some(p => p.id === draft.property && p.status !== 'Archived')) { setError('Choose an active property.'); return }
    const old = state.users.find(u => u.id === editing)
    const user: User = { ...draft, id: editing || `USR-${crypto.randomUUID().slice(0, 6).toUpperCase()}`, name, email, property: draft.role === 'System Admin' ? '' : draft.property, active: old?.active ?? true }
    update(editing ? 'User Update' : 'User Create', `${editing ? 'Updated' : 'Created'} demo account ${name}.`, store => ({ ...store, users: editing ? store.users.map(u => u.id === editing ? user : u) : [...store.users, user] }))
    setNotice(`${name} saved in preview only. No Supabase account, password or email was created.`); reset()
  }
  return <div className="ad-main"><Notice>{notice}</Notice><Panel title={editing ? 'Edit User Account' : 'Create and Manage Accounts'}><form onSubmit={save}><div className="ad-four-fields"><label>Full Name<input id="ad-user-name" required maxLength={100} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>Email<input type="email" required maxLength={160} value={draft.email} onChange={e => setDraft({ ...draft, email: e.target.value })} /></label><label>Role<select value={draft.role} disabled={editing === 'USR-001'} onChange={e => setDraft({ ...draft, role: e.target.value as Role })}>{roles.map(r => <option key={r}>{r}</option>)}</select></label><label>Property<select value={draft.property} disabled={draft.role === 'System Admin'} required={draft.role !== 'System Admin'} onChange={e => setDraft({ ...draft, property: e.target.value })}><option value="">Select property...</option>{state.properties.filter(p => p.status !== 'Archived').map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><p className="ad-muted">Temporary passwords will be managed by the authentication backend later. Do not enter real credentials in this demo.</p>{error && <p className="ad-error" role="alert">{error}</p>}<div className="ad-actions ad-end"><button type="button" onClick={reset}>Cancel</button><button className="ad-primary">{editing ? 'Save Account' : 'Create Account'}</button></div></form><Table label="User accounts"><thead><tr>{['User ID', 'Name / Email', 'Role', 'Property', 'Status', 'Actions'].map(v => <th key={v}>{v}</th>)}</tr></thead><tbody>{state.users.filter(u => matches(search, u.id, u.name, u.email, u.role)).map(u => <tr key={u.id}><th>{u.id}</th><td>{u.name}<br /><small>{u.email}</small></td><td>{u.role}</td><td>{state.properties.find(p => p.id === u.property)?.name || 'System-wide'}</td><td><Toggle label={u.active ? 'Active' : 'Disabled'} checked={u.active} disabled={u.id === 'USR-001'} onChange={active => { update('User Status', `${u.name} ${active ? 'enabled' : 'disabled'} in demo.`, old => ({ ...old, users: old.users.map(item => item.id === u.id ? { ...item, active } : item) })); setNotice('Account status updated locally; no real access was changed.') }} /></td><td><button aria-label={`Edit ${u.name}`} onClick={() => { setEditing(u.id); setDraft({ name: u.name, email: u.email, role: u.role, property: u.property }); document.getElementById('ad-user-name')?.focus() }}>Edit</button></td></tr>)}</tbody></Table></Panel>
    <Panel title="Assign Roles and Permissions" actions={<select aria-label="Permission role" value={permissionRole} onChange={e => setPermissionRole(e.target.value as Role)}>{roles.map(r => <option key={r}>{r}</option>)}</select>}><Permissions key={permissionRole} role={permissionRole} /></Panel>
    <Panel title="Password Management"><label>Select Account<select value={passwordUser} onChange={e => setPasswordUser(e.target.value)}>{state.users.map(u => <option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></label><p className="ad-muted">Preview the recovery workflow without changing passwords or sending messages.</p><div className="ad-actions"><button onClick={() => setModal({ kind: 'reset', id: passwordUser })}>Preview Password Reset</button><button className="ad-primary" onClick={() => setModal({ kind: 'link', id: passwordUser })}>Preview Reset Link</button></div></Panel>
    <Panel title="Security Policy"><Toggle label="Require First-Login Password Change" checked={policy} onChange={setPolicy} /><button className="ad-primary" onClick={() => { update('Security Policy', 'Updated demo first-login password policy.', old => ({ ...old, forcePassword: policy })); setNotice('Preview policy saved. Authentication settings remain unconnected.') }}>Apply Demo Policy</button></Panel>
    <Panel title="Monitor Active Sessions"><Table label="User sessions"><thead><tr><th>User</th><th>Session Details</th><th>Status</th><th>Action</th></tr></thead><tbody>{state.sessions.map(s => <tr key={s.id}><th>{s.user}</th><td>{s.details}</td><td><Badge value={s.active ? 'Active' : 'Ended'} /></td><td><button className="ad-danger" disabled={s.current || !s.active} onClick={() => setModal({ kind: 'session', id: s.id })}>{s.current ? 'Current Session' : 'Terminate Session'}</button></td></tr>)}</tbody></Table></Panel>
    <Panel title="Login History and Audit Trail" actions={<><input aria-label="Login history date" type="date" value={date} onChange={e => setDate(e.target.value)} /><button onClick={() => { csvDownload('demo-login-history.csv', [['User', 'Time', 'IP (documentation range)', 'Result'], ...history.map(l => [l.user, l.time, l.ip, l.result])]); update('Data Export', 'Exported filtered demo login history.') }}>Export Login CSV</button></>}><Table label="Login history"><thead><tr><th>User</th><th>Time</th><th>IP Address</th><th>Result</th></tr></thead><tbody>{history.map(l => <tr key={l.id}><th>{l.user}</th><td>{l.time.replace('T', ' ')}</td><td>{l.ip}</td><td><Badge value={l.result} /></td></tr>)}{!history.length && <tr><td colSpan={4}>No matching login events.</td></tr>}</tbody></Table><p className="ad-muted">All IP addresses are illustrative documentation addresses. No live login activity is tracked.</p></Panel>
    {modal && <Modal title={modal.kind === 'session' ? 'End Demo Session?' : 'Password Recovery Preview'} onClose={() => setModal(null)}><p>{modal.kind === 'session' ? 'This marks the sample session as ended. It does not log anyone out of a real system.' : `Selected account: ${state.users.find(u => u.id === modal.id)?.email}. This preview records the requested recovery action, but does not create a reset token, send an email or change a password.`}</p><div className="ad-actions ad-end"><button onClick={() => setModal(null)}>Cancel</button><button className="ad-primary" onClick={() => { if (modal.kind === 'session') update('Session Termination', 'Ended a demo session.', old => ({ ...old, sessions: old.sessions.map(s => s.id === modal.id && !s.current ? { ...s, active: false } : s) })); else update('Password Recovery Preview', `Previewed ${modal.kind === 'reset' ? 'password reset' : 'reset link'} for ${state.users.find(u => u.id === modal.id)?.name}.`); setNotice('Demo action recorded in Audit Logs. No authentication service was contacted.'); setModal(null) }}>Confirm Preview</button></div></Modal>}
  </div>
}
